### ISSUE TITLE
Not able to start the camea and start the presentation

### ISSUE THREAD

**Issue by KeerthiTM** [alen-mon/SmartPresentation_using_Gesture_Recognition#1]
Camera not turning on after starting camera
Start presentation returns to the home screen and doesnt start the presentation
![errorlog](https://user-images.githubusercontent.com/73210750/234618091-b85fe2e5-65d5-43bc-9b56-7bd78163cf34.png)

**Comment by alen-mon** [comment]
## Issue-Not able to start the camea and start the presentation #1

#### #issue1: It seems like there is an issue with getting the IP camera Info .
#### #The error is also not handled properly 

I have fixed the error and handled the exception.

![Fix](https://user-images.githubusercontent.com/63594718/234625215-3aefbe48-aff9-4319-9b64-6b5f8dcfb292.png)


#### #issue2 :I can also see that there is a bug in the camera mounting code for the presentation script "main.py"

The main.py has been fixed.
![Fix](
![image](https://user-images.githubusercontent.com/63594718/234625325-97df0855-ff8c-4e31-a8d7-9f8d857782de.png)


I have also fixed some additonal bugs related to the camera and main.py script.
Thank you

**Comment by alen-mon** [comment]
## Issue-Not able to start the camea and start the presentation #1

#### #issue1: It seems like there is an issue with getting the IP camera Info .
#### #The error is also not handled properly 

I have fixed the error and handled the exception.

![Fix](https://user-images.githubusercontent.com/63594718/234625215-3aefbe48-aff9-4319-9b64-6b5f8dcfb292.png)


#### #issue2 :I can also see that there is a bug in the camera mounting code for the presentation script "main.py"

The main.py has been fixed.
![Fix](
![image](https://user-images.githubusercontent.com/63594718/234625325-97df0855-ff8c-4e31-a8d7-9f8d857782de.png)


I have also fixed some additonal bugs related to the camera and main.py script.
Thank you
